### ISSUE TITLE
Add PersistedModel Methods that are not exposed via REST (findOrCreate(), etc)

### ISSUE THREAD

**Issue by jbcpollak** [strongloop/loopback-connector-remote#40]
it looks like the `PersistedModel.findOrCreate()` method is not implemented. When I run it with a `remote` object I get:

```
Error: Cannot call MyObj.findOrCreate(). The findOrCreate method has not been setup. The PersistedModel has not been correctly attached to a DataSource!
    at throwNotAttached (/.../node_modules/loopback/lib/persisted-model.js:62:11)
    at Function.findOrCreate (/.../node_modules/loopback/lib/persisted-model.js:145:5)
    at ....
```

**Comment by richardpringle** [comment]
Hey @jbcpollak, the only methods that are (and can be) implemented are the methods exposed to REST. In other words, any of the methods you can see in the loopback-component-explorer. 

LoopBack-connector-remote is meant to function much in the same way as [LoopBack-connector-rest](https://github.com/strongloop/loopback-connector-rest) only instead of using a template driven approach, it simply uses [strong-remoting](https://github.com/strongloop/strong-remoting) to populate the remoting-metadata since the REST-API datasource is another LoopBack app.

If you think it would be beneficial, I can throw a feature request label on this issue and maybe it can be implemented in the future? I would ask that you change both your description and the title though to clearly define the request (say adding PersistedModel methods that aren't exposed to REST for example).

**Comment by jbcpollak** [comment]
@richardpringle If I understand what you are saying, would it make more sense for this to be a feature request of strong-remoting, so all remote methods support promises? Can that be handled at that level? I realized when implementing custom remote methods the lack of promises was frustrating.

**Comment by richardpringle** [comment]
@jbcpollak, I think the feature still belongs in this repo. Also, supporting promises is a separate issue.

**Comment by doublemarked** [comment]
@richardpringle shouldn't the connector aim to fill in missing methods like `findOrCreate` with work-a-likes? Much like how the juggler has fallback implementations, like this one for `findOrCreate`: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1008-L1026

**Comment by richardpringle** [comment]
@doublemarked, I believe that this connector is designed with similar motivation as the LoopBack SDKs, taking advantage of the sharedClass/sharedMethods from strong-remoting to communicate to a client (another LoopBack application in this case). 

These are just semantics, but I wouldn't say _*should*_ just because I don't believe that it was the initial goal. I do however completely agree that it would be great to have these implemented exactly as you said to improve upon the connector. 

Either way, I don't think it'll change the priority of this issue, so we shouldn't get caught up in semantics :smile:.

**Comment by doublemarked** [comment]
Okay, thanks for the reply! You're right, "should" was probably a bit too strong of a word :)

**Comment by jbcpollak** [comment]
Just wondering - will this ever be done? It seems very odd to me that the various connectors don't have to conform to the same external API.
