### ISSUE TITLE
Handle relations locally

### ISSUE THREAD

**Issue by ExTheSea** [strongloop/loopback-connector-remote#84]
# Description/Steps to reproduce

1. Create two Loopback APIs with each containing a model with all CRUD operations.
2. Now create another Loopback API and copy the model definitions of the two models from the two APIs.
3. Connect them to the original CRUD APIs using the remote connector.
4. Create a new relation between the two copied models
5. Test the relation using either the /model1/{id}/relation method or the include filter

# Link to reproduction sandbox
https://github.com/ExTheSea/loopback-remote-relations-issue

# Expected result
The expected behavior would be that the connector handles the relation correctly like other connectors do by finding the related instances in the API and not just forwards the entire request to the connected API.

The rest connector does this slightly better as it at least attempts to handle the /model1/{id}/relation. 
It is correctly looking for the model1 instance by calling /model1/{id} and then using the result to create a filter ({"where": {"foreignKey": id}}) used when calling the related model. Unfortunately there is a problem in the rest connector where filters aren't passed along properly and as such cannot be parsed by the related model but at least it doesn't throw an error and instead returns all instances from the related model

# Additional information

win32 x64 8.9.1

+-- loopback@3.17.1
+-- loopback-boot@2.27.0
+-- loopback-component-explorer@5.2.0
+-- loopback-connector-remote@3.3.0
+-- loopback-connector-rest@3.1.0

**Comment by mitsos1os** [comment]
I believe this tackles an other conversation. From what I can tell there are two cases for similar scenarios:
1. The source service *(in your sandbox remote-source1)*, knows how to handle the relation. (The relation is defined in remote-source1's model definition), so it is properly forwarded in source service
2. The relation is defined in the top layer *(your remoting-parent service)* and should be handled there, with the behavior you described.

Whether a single way is chosen is not my decision to take, however from a really quick look the 2nd behavior could be easily implemented (or toggled through an option if case 1 also remains supported), by just not allowing the remote connector init code to override **__relation__** methods with the remoteProxy function call. This way since all related methods are instance (prototype) methods, the parent model retrieval should work as is, and then the related model actual call will use the underlying data source of the second (related) model...

If one of the operators such as @bajtos agrees with this kind of implementation, I could submit a PR when I find some time

**Comment by bajtos** [comment]
Thank you @mitsos1os for the summary. I think both approaches described in your comment are valid ones, possibly depending on the scenario. It would be great if our remote connector was able to support both of them, and even better if it could automatically decide which approach to use: When both related models are living on the same backend server, then let the server handle relations. When the models are living on different servers, then the relations should be handled locally.

I am afraid we don't have bandwidth to implement this feature ourselves, but contributions are welcome!
